name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t skymnok/react-test -f ./client/dockerfile.dev ./client
          docker run -e CI=true skymnok/react-test npm test

      - name: Set Service Key
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-366614

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t skymnok/multi-client-k8s-gh:latest -t skymnok/multi-client-k8s-gh:${{ env.SHA }} -f ./client/dockerfile ./client
          docker build -t skymnok/multi-server-k8s-pgfix-gh:latest -t skymnok/multi-server-k8s-pgfix-gh:${{ env.SHA }} -f ./server/dockerfile ./server
          docker build -t skymnok/multi-worker-k8s-gh:latest -t skymnok/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/dockerfile ./worker

      - name: Push
        run: |-
          docker push skymnok/multi-client-k8s-gh:latest
          docker push skymnok/multi-server-k8s-pgfix-gh:latest
          docker push skymnok/multi-worker-k8s-gh:latest
          
          docker push skymnok/multi-client-k8s-gh:${{ env.SHA }}
          docker push skymnok/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          docker push skymnok/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s-deployment
          kubectl set image deployments/server-deployment server=skymnok/multi-server-k8s-pgfix-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=skymnok/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=skymnok/multi-worker-k8s-gh:${{ env.SHA }}